pool:
  vmImage: "ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: 3.0.100

  - task: DotNetCoreCLI@2
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      projects: "**/*.csproj"
      arguments: "--configuration $(buildConfiguration)"
