//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orleans.Persistence.CosmosDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orleans.Persistence.CosmosDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ClearState(grainType, id, eTag, isDelete) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  if (!grainType) throw new Error(&apos;grainType is required&apos;);
        ///  if (!id) throw new Error(&apos;id is required&apos;);
        ///
        ///  var query = &apos;SELECT * FROM c WHERE c.GrainType = &quot;&apos; + grainType + &apos;&quot; AND c.id = &quot;&apos; + id + &apos;&quot;&apos;;
        ///  var accept = collection.queryDocuments(collection.getSelfLink(), query, {},
        ///    function (err, docs, responseOptions) {
        ///      if (err)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClearState {
            get {
                return ResourceManager.GetString("ClearState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ReadState(grainType, id) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  if (!grainType) throw new Error(&apos;grainType is required&apos;);
        ///  if (!id) throw new Error(&apos;id is required&apos;);
        ///
        ///  var query = &apos;SELECT * FROM c WHERE c.GrainType = &quot;&apos; + grainType + &apos;&quot; AND c.id = &quot;&apos; + id + &apos;&quot;&apos;;
        ///  var accept = collection.queryDocuments(collection.getSelfLink(), query, {},
        ///    function (err, docs, responseOptions) {
        ///      if (err) throw new Error(&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadState {
            get {
                return ResourceManager.GetString("ReadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function WriteState(entity) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  if (!entity) throw new Error(&apos;entity is required&apos;);
        /// 
        ///  var query = &apos;SELECT c.id, c._self FROM c WHERE c.GrainType = &quot;&apos; + entity.GrainType + &apos;&quot; AND c.id = &quot;&apos; + entity.id + &apos;&quot;&apos;;
        ///  var accept = collection.queryDocuments(collection.getSelfLink(), query, {},
        ///    function (err, docs, responseOptions) {
        ///      if (err) throw new Error(&quot;Error: &quot; + err.message);
        ///
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteState {
            get {
                return ResourceManager.GetString("WriteState", resourceCulture);
            }
        }
    }
}
