//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orleans.Clustering.CosmosDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orleans.Clustering.CosmosDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function DeleteAllEntries(clusterId) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  var query = &apos;SELECT * FROM c WHERE c.ClusterId = &quot;&apos; + clusterId + &apos;&quot;&apos;;
        ///  var accept = collection.queryDocuments(collection.getSelfLink(), query, {},
        ///    function (err, silos, responseOptions) {
        ///      if (err) throw new Error(&quot;Error: &quot; + err.message);
        ///
        ///      if (silos.length &gt; 0) {
        ///
        ///        silos.forEach(s =&gt; {
        ///          collection.deleteDocu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteAllEntries {
            get {
                return ResourceManager.GetString("DeleteAllEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetAliveGateways(clusterId) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  var query = &apos;SELECT * FROM c WHERE c.ClusterId = &quot;&apos; + clusterId +
        ///    &apos;&quot; AND c.EntityType = &quot;SiloEntity&quot; AND c.Status = &quot;Active&quot; AND is_defined(c.ProxyPort) AND c.ProxyPort &lt;&gt; 0&apos;;
        ///  var accept = collection.queryDocuments(collection.getSelfLink(), query, {},
        ///    function (err, docs, responseOptions) {
        ///      if (err) throw new Error(&quot;Error: &quot; + er [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAliveGateways {
            get {
                return ResourceManager.GetString("GetAliveGateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function InsertSiloEntity(siloEntity, newVersionEntity) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  var entityExistQuery = &apos;SELECT c.id FROM c WHERE c.id = &quot;&apos; + siloEntity.id + &apos;&quot;&apos;;
        ///  var existAccepted = collection.queryDocuments(collection.getSelfLink(), entityExistQuery, {},
        ///    function (err, found) {
        ///      if (!existAccepted) throw new Error(&apos;Unable to query for SiloEntity&apos;);
        ///
        ///      if (found.length &gt; 0) {
        ///        resp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertSiloEntity {
            get {
                return ResourceManager.GetString("InsertSiloEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ReadAll(clusterId) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  var query = &apos;SELECT * FROM c WHERE c.ClusterId = &quot;&apos; + clusterId + &apos;&quot;&apos;;
        ///  var accept = collection.queryDocuments(collection.getSelfLink(), query, {},
        ///    function (err, docs, responseOptions) {
        ///      if (err) throw new Error(&quot;Error: &quot; + err.message);
        ///
        ///      if (docs.length &gt; 0) {
        ///        var clusterVersion = docs.find(d =&gt; d.EntityType === &quot;ClusterVersi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadAll {
            get {
                return ResourceManager.GetString("ReadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ReadSiloEntity(clusterId, siloId) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  var query = &apos;SELECT * FROM c WHERE c.ClusterId = &quot;&apos; + clusterId + &apos;&quot;&apos;;
        ///  var accept = collection.queryDocuments(collection.getSelfLink(), query, {},
        ///    function (err, docs, responseOptions) {
        ///      if (err) throw new Error(&quot;Error: &quot; + err.message);
        ///
        ///      if (docs.length &gt; 0) {
        ///        var clusterVersion = docs.find(d =&gt; d.EntityType == [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadSiloEntity {
            get {
                return ResourceManager.GetString("ReadSiloEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function UpdateIAmAlive(siloEntityId, iAmAliveTime) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  var entityExistQuery = &apos;SELECT * FROM c WHERE c.id = &quot;&apos; + siloEntity.id + &apos;&quot;&apos;;
        ///  var existAccepted = collection.queryDocuments(collection.getSelfLink(), entityExistQuery, {},
        ///    function (err, found) {
        ///      if (!existAccepted) throw new Error(&apos;Unable to query for SiloEntity&apos;);
        ///
        ///      if (found.length &gt; 0) {
        ///        var siloFou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateIAmAlive {
            get {
                return ResourceManager.GetString("UpdateIAmAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function InsertSiloEntity(siloEntity, newVersionEntity) {
        ///  var context = getContext();
        ///  var collection = context.getCollection();
        ///  var response = context.getResponse();
        ///
        ///  var entityExistQuery = &apos;SELECT c.id, c._self FROM c WHERE c.id = &quot;&apos; + siloEntity.id + &apos;&quot;&apos;;
        ///  var existAccepted = collection.queryDocuments(collection.getSelfLink(), entityExistQuery, {},
        ///    function (err, found) {
        ///      if (!existAccepted) throw new Error(&apos;Unable to query for SiloEntity&apos;);
        ///
        ///      if (found.length &gt; 0) {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateSiloEntity {
            get {
                return ResourceManager.GetString("UpdateSiloEntity", resourceCulture);
            }
        }
    }
}
